alert("JavaScript started 💗");const S=JSON.parse(localStorage.getItem('yog_state')||'{}');
const save=()=>localStorage.setItem('yog_state',JSON.stringify(S));
const vibes=['🎀 Girly Girl','🖤 Goth','🧸 Soft & Cozy','💅 Confident & Sassy','😂 Funny & Chaotic','📚 Smart & Focused','🌿 Calm & Peaceful','🪩 Energetic & Bubbly','🌙 Quiet & Mysterious','✨ Custom'];
const styles=['💗 Sweet & gentle','🎯 Straightforward','😂 Funny','🌟 Motivational','😌 Chill','💅 A little sassy','✨ Mix it up'];
const emoji=['Lots 💗✨😭','Sometimes','None'],modes=['🌱 Beginner','📚 Standard','🔥 Exam Mode','🧠 Challenge Me'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function choices(id,arr,key,multi=false){$(id).innerHTML=arr.map(x=>`<button class="${(S[key]||[]).includes(x)?'selected':''}" data-v="${x}">${x}</button>`).join('');$(id).onclick=e=>{let b=e.target.closest('button');if(!b)return;S[key]=S[key]||[];if(multi)S[key]=S[key].includes(b.dataset.v)?S[key].filter(x=>x!==b.dataset.v):[...S[key],b.dataset.v];else S[key]=[b.dataset.v];save();choices(id,arr,key,multi)}}
choices('#vibes',vibes,'vibes',true);choices('#styles',styles,'style');choices('#emoji',emoji,'emoji');choices('#modes',modes,'studyMode');
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='home')home();if(id==='profile')profile();if(id==='customize'){choices('#vibes',vibes,'vibes',true);choices('#styles',styles,'style');choices('#emoji',emoji,'emoji');$('#girlName').value=S.name||'';$('#custom').value=S.custom||''}}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#saveProfile').onclick=()=>{S.name=$('#girlName').value.trim();S.custom=$('#custom').value.trim();save();go('home')};
function home(){let h=new Date().getHours();$('#greeting').textContent=(h<12?'Good morning':h<18?'Good afternoon':'Good evening')+', '+(S.name||'girl')+' 💗';$('#mood').textContent=S.mood?'Today you said: '+S.mood+' 💗':'';$('#plans').innerHTML=(S.plans||[]).map(x=>`<p>☐ ${x}</p>`).join('')||'<p>No plans yet.</p>'}
function profile(){$('#profileName').textContent=S.name||'Your Other Girl';$('#profileVibe').textContent=(S.vibes||[]).join(' • ')||'Your pocket girl is here.'}
const nav=`<nav class="bottom"><button data-go="home">🏠<small>Home</small></button><button data-go="chat">💬<small>Chat</small></button><button data-go="study">📚<small>Study</small></button><button data-go="tools">✨<small>Tools</small></button><button data-go="profile">👤<small>Me</small></button></nav>`;$('#nav').outerHTML=nav;$$('.bottom [data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#moods').innerHTML=['😊 Great','🙂 Okay','😐 Meh','😔 Not great','😭 Rough day'].map(x=>`<button data-mood="${x.slice(2)}">${x[0]}</button>`).join('');$('#moods').onclick=e=>{let b=e.target.closest('button');if(b){S.mood=b.dataset.mood;save();home()}};
$('#addPlan').onclick=()=>{let x=prompt('What do you want to add to your day?');if(x){S.plans=S.plans||[];S.plans.push(x);save();home()}};
function addMsg(w,t){let d=document.createElement('div');d.className='msg '+w;d.textContent=t;$('#messages').appendChild(d);$('#messages').scrollTop=999999}
async function send(){let text=$('#message').value.trim();if(!text)return;addMsg('you',text);$('#message').value='';addMsg('girl','…');let last=$('#messages').lastChild;try{let r=await fetch((window.YOG_API||'http://localhost:8787')+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,profile:{name:S.name||'',vibes:S.vibes||[],style:(S.style||[])[0]||'',emoji:(S.emoji||[])[0]||'',custom:S.custom||''}})});let j=await r.json();last.textContent=j.reply||'I’m here, girl 💗';}catch(e){last.textContent='The AI connection is not configured yet. You can still use the app prototype while the backend is connected.'}}
$('#send').onclick=send;$('#message').onkeydown=e=>{if(e.key==='Enter')send()};$$('[data-starter]').forEach(b=>b.onclick=()=>{$('#message').value=b.dataset.starter;send()});
$$('[data-study]').forEach(b=>b.onclick=()=>{$('#studyBox').classList.remove('hidden');$('#studyBox').innerHTML=`<h3>${b.dataset.study} 💗</h3><p>Tell me the subject, topic and what you need help with.</p><textarea id="studyText" placeholder="Type here..."></textarea><button class="primary" style="margin-top:10px" onclick="studyAsk()">Ask my pocket girl →</button>`});
window.studyAsk=async()=>{let t=$('#studyText').value;$('#studyBox').innerHTML='<h3>Working on it… 💗</h3>';try{let r=await fetch((window.YOG_API||'http://localhost:8787')+'/api/study',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:t,mode:(S.studyMode||[])[0]||'📚 Standard'})});let j=await r.json();$('#studyBox').innerHTML='<h3>Study help 💗</h3><p>'+esc(j.reply||'')+'</p>'}catch(e){$('#studyBox').innerHTML='<p>Connect the backend to use the AI study engine.</p>'}};
function esc(x){return String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
$$('[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool));
function tool(t){$('#toolBox').classList.remove('hidden');let title={journal:'📔 Journal',todo:'📝 To-do list',planner:'📅 Planner',goals:'🎯 Goals',routine:'⏰ Routines',brain:'💡 Brain dump'}[t];$('#toolBox').innerHTML=`<h3>${title}</h3><textarea id="toolText" placeholder="Write here..."></textarea><button class="primary" style="margin-top:10px" onclick="saveTool('${t}')">Save</button>`;$('#toolText').value=(S.tools||{})[t]||''}
window.saveTool=(t)=>{S.tools=S.tools||{};S.tools[t]=$('#toolText').value;save();alert('Saved on this device 💗')};
$$('[data-problem]').forEach(b=>b.onclick=()=>{$('#problemBox').innerHTML=`<div class="card"><b>${b.dataset.problem}</b><p>I'm listening. 💗 Do you want me to just listen, help you understand, or help you think through what to do?</p><button data-go="chat">Talk to me →</button></div>`;$('#problemBox [data-go]').onclick=()=>go('chat')});
function modal(html){$('#modal').classList.remove('hidden');$('#modal').innerHTML=`<div class="modalbox">${html}</div>`}
$('#privacy').onclick=()=>modal('<h2>🔒 Private Girl Mode</h2><p>Production mode should use secure account authentication, encrypted storage and device authentication. This prototype keeps local data in browser storage only.</p><button onclick="closeModal()">Close</button>');
$('#memory').onclick=()=>modal('<h2>🧠 What does she remember?</h2><p>This prototype remembers your selected preferences and tool notes on this device.</p><button onclick="clearData()">Delete my saved data</button> <button onclick="closeModal()">Close</button>');
$('#premium').onclick=()=>modal('<h2>💎 Premium</h2><p><b>No advertisements at all.</b> Premium can add advanced personalization, extra themes, advanced study features and planning tools. Core help stays useful without Premium.</p><button onclick="closeModal()">Close</button>');
$('#about').onclick=()=>modal('<h2>Your Other Girl 💗</h2><p>“I’m your pocket girl.” An AI-powered assistant for girls to talk, study, organise and work through everyday problems.</p><p>For serious situations, the app should encourage appropriate trusted real-world support.</p><button onclick="closeModal()">Close</button>');
window.closeModal=()=>$('#modal').classList.add('hidden');window.clearData=()=>{localStorage.removeItem('yog_state');location.reload()};
home();profile();go('welcome');
/* Functional chat demo */
(function(){function inp(){return document.querySelector('#chatInput, textarea[placeholder*="message" i], input[placeholder*="message" i], textarea')}function btn(){return document.querySelector('#sendBtn')||Array.from(document.querySelectorAll('button')).find(b=>(b.textContent||'').trim()==='➤')}function area(){return document.querySelector('#chatMessages,.chat-messages,.messages,.chat-body')||document.querySelector('main')}function bubble(t,u){let a=area();if(!a)return;let w=document.createElement('div');w.className='chat-message '+(u?'user-message':'ai-message');let b=document.createElement('div');b.className='message-bubble';b.textContent=t;w.appendChild(b);a.appendChild(w);a.scrollTop=a.scrollHeight}function send(){let i=inp();if(!i)return;let t=i.value.trim();if(!t)return;bubble(t,true);i.value='';i.focus();setTimeout(()=>bubble('I'm here, girl 💗 Tell me more. Do you want me to just listen, help you understand, or help you figure out what to do?',false),450)}document.addEventListener('click',e=>{let b=e.target.closest('button');if(b&&(b.id==='sendBtn'||(b.textContent||'').trim()==='➤'))send()});document.addEventListener('keydown',e=>{if(e.target.matches('textarea')&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});function ensure(){let i=inp();if(i)return;let f=document.querySelector('.chat-input,.chat-footer,footer')||document.querySelector('main');if(!f)return;let row=document.createElement('div');row.className='chat-input-row';let x=document.createElement('textarea');x.id='chatInput';x.placeholder="What's on your mind, girl? 💗";let b=document.createElement('button');b.id='sendBtn';b.textContent='➤';row.append(x,b);f.appendChild(row)}setTimeout(ensure,100);setTimeout(ensure,800)})();
alert("Your Other Girl is working 💗");
